apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wbti3dky7-python
  janus-idp.io/tekton: wbti3dky7-python
  backstage.io/kubernetes-id: wbti3dky7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbti3dky7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
